fix: abort when matrix.txt is empty

diff --git a/.github/actions/generate-chart-matrix/action.yml b/.github/actions/generate-chart-matrix/action.yml
--- a/.github/actions/generate-chart-matrix/action.yml
+++ b/.github/actions/generate-chart-matrix/action.yml
@@ -23,12 +23,6 @@ runs:
       uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
       with:
         dir_names: "true"
-    - name: Abort if no changed files
-      shell: bash
-      if: steps.changed-files.outputs.all_modified_files == ''
-      run: |
-        echo "No changed files found. This workflow is only triggered when there are changes to the code. Aborting."
-        exit 1
     - name: Generate matrix
       shell: bash
       id: set-chart-versions
@@ -70,6 +64,12 @@ runs:
           fi
         done
         cat matrix_versions.txt
+
+        # Check if matrix_versions.txt has any content beyond the header
+        if [ "$(cat matrix_versions.txt)" = "matrix:" ]; then
+          echo "No changed files found. This workflow is only triggered when there are changes to the code. Aborting."
+          exit 1
+        fi
 
         matrix="$(cat matrix_versions.txt | yq -o=json '.matrix' | jq -c '{ "include": . }' | jq -c 'walk(if type == "number" then tostring else . end)')"
         echo "matrix=${matrix}" | tee -a $GITHUB_OUTPUT
